import React, { useState } from "react";
import {
  BookOpen,
  Brain,
  ListTodo,
  BarChart3,
} from "lucide-react";
import Tasks from "../pages/Tasks.jsx";

const ModuleDetailPage = ({ module, onBack }) => {
  const [activeTab, setActiveTab] = useState("tasks");

  return (
    /* PAGE CONTAINER — FIXED HEIGHT */
    <div className="h-full w-full flex flex-col overflow-hidden">

      {/* HEADER (STATIC) */}
      <div
        className={`w-full ${module.color || "bg-blue-500"} text-white px-8 py-6 shadow-sm flex flex-col gap-4`}
      >
        <div className="flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-bold">{module.name}</h1>
          </div>

          {/* Quick Stats */}
          <div className="flex gap-8 text-white/90">
            <div className="flex items-center gap-3 mb-1">
              <span className="bg-white/20 px-2 py-0.5 rounded text-xs font-bold uppercase">
                {module.type || "General"}
              </span>
              <span className="bg-white/20 px-2 py-0.5 rounded text-xs font-bold uppercase">
                Level {module.difficulty || 3}/5
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* TABS (STATIC) */}
      <div className="flex items-center px-8 border-b border-gray-200 bg-white">
        {[
          { id: "tasks", label: "Study Tasks", icon: ListTodo },
          { id: "ai-plan", label: "AI Syllabus", icon: Brain },
          { id: "resources", label: "Notes & Docs", icon: BookOpen },
          { id: "progress", label: "Progress", icon: BarChart3 },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 px-6 py-4 border-b-2 transition-all font-medium text-sm
              ${
                activeTab === tab.id
                  ? "border-gray-900 text-gray-900"
                  : "border-transparent text-gray-500 hover:text-gray-700"
              }
            `}
          >
            <tab.icon size={18} />
            {tab.label}
          </button>
        ))}
      </div>

      {/* TAB CONTENT — ONLY THIS SCROLLS */}
      <div className="flex-1 w-full overflow-y-auto bg-gray-50 scrollbar-hide">
        {activeTab === "tasks" && (
          
            <Tasks module={module} />
          
        )}

        {activeTab === "ai-plan" && (
          <div className="p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              AI-Generated Syllabus
            </h2>
            <div className="bg-white rounded-xl shadow-sm p-6">
              <p className="text-gray-600">
                Your personalized learning plan generated by AI will appear here.
              </p>
              <p className="text-gray-500 text-sm mt-4">Coming soon...</p>
            </div>
          </div>
        )}

        {activeTab === "resources" && (
          <div className="p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Notes & Documents
            </h2>
            <div className="bg-white rounded-xl shadow-sm p-6 text-center py-20">
              <div className="text-6xl mb-4 opacity-30">📄</div>
              <p className="text-gray-500">No resources uploaded yet.</p>
              <p className="text-gray-400 text-sm mt-2">
                Add notes, PDFs, links, or images here.
              </p>
            </div>
          </div>
        )}

        {activeTab === "progress" && (
          <div className="p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Progress Overview
            </h2>
            <div className="bg-white rounded-xl shadow-sm p-6 text-center py-20">
              <div className="text-6xl mb-4 opacity-30">📊</div>
              <p className="text-gray-500">
                Detailed stats and charts coming soon.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ModuleDetailPage;
