"""fix task enums priority status

Revision ID: 20d186a52dcc
Revises: c8ba063eadec
Create Date: 2026-04-12 11:46:20.448365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20d186a52dcc'
down_revision: Union[str, Sequence[str], None] = 'c8ba063eadec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='taskstatus'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevel'),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='taskstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='taskstatus'),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevel'),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='taskstatus'),
               nullable=True)
    # ### end Alembic commands ###
