"""add_custom_slot_times

Revision ID: 3d4ebd0fb8b9
Revises: dfd99d75f5a0
Create Date: 2026-04-13 19:26:32.728755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4ebd0fb8b9'
down_revision: Union[str, Sequence[str], None] = 'dfd99d75f5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
