"""add_onboarding_completed_to_users

Revision ID: e37699efa63d
Revises: 442ff8058ac5
Create Date: 2026-04-10 09:54:40.019712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37699efa63d'
down_revision: Union[str, Sequence[str], None] = '442ff8058ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_exams_user_id', 'exams', type_='foreignkey')
    op.drop_constraint('fk_modules_user_id', 'modules', type_='foreignkey')
    op.drop_constraint('fk_sessions_user_id', 'pomodoro_sessions', type_='foreignkey')
    op.drop_constraint('uq_slot_preferences_user_slot', 'slot_preferences', type_='unique')
    op.drop_constraint('fk_preferences_user_id', 'slot_preferences', type_='foreignkey')
    op.drop_constraint('fk_tasks_user_id', 'tasks', type_='foreignkey')
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.drop_constraint('fk_routine_user_id', 'weekly_routine', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_routine_user_id', 'weekly_routine', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'onboarding_completed')
    op.create_foreign_key('fk_tasks_user_id', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_preferences_user_id', 'slot_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_slot_preferences_user_slot', 'slot_preferences', ['user_id', 'slot_name'])
    op.create_foreign_key('fk_sessions_user_id', 'pomodoro_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_modules_user_id', 'modules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_exams_user_id', 'exams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
